# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Cache@2
  displayName: "Cache Packages"
  inputs:
    key: 'gradle-cache'
    path: '$(System.DefaultWorkingDirectory)/.gradle/caches/modules-2/files-2.1'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    gradleOptions: '-Xmx4096m'
    sonarQubeRunAnalysis: false
    pmdRunAnalysis: true
    spotBugsAnalysis: false


